version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-om
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27021:27017" 
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-om
    restart: always
    depends_on:
      - mongo
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    networks:
      - my_network

  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: node-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge
